name: Vite Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
    
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: pnpm install
        run: |
          pnpm install

      - name: check
        run: |
          pnpm run lint:tsc

      - name: Build
        run: |
          pnpm run build

      - name: Deploy to release
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: release
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.DEPLOY }}

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'ubuntu'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: '/home/hyz/todolist'
          port: 22345